### ISSUE TITLE
*Cries in End Reborn*

### ISSUE THREAD

**Issue by Rebel459** [Immodernist/Endorium#2]
![CE9CCFD9-4C74-4116-AC93-8E004C20A7D5](https://github.com/Immodernist/Endorium/assets/131760345/e49547ed-2fa6-4b02-b259-4c285f37afd5)
I’ve been working on a mod with a similar name and the namespace end_reborn as an overhaul of an existing mod of mine for a while now… you don’t suppose the name similarity would be an issue, do you?

You beat me to it lmao

**Comment by Rebel459** [comment]
Ignore the New Biomes part, probably gonna keep it as just tweaks for the forseeable future lol

**Comment by Immodernist** [comment]
Well, how to say it, sorry, but the mod was created in 2018 by that name on CurseForge, though I am planning to rename it, as I already did on this platform, because back at the time it was quite a confusion with Tech Reborn and Hardcore Ender Expansion, and currently the mod features are way different from the initial.

**Comment by Rebel459** [comment]
RIP on my end, hope it doesn’t become an issue because I really don’t feel like re-doing all those recipes and naming synergy yet again lol. At least the names are different and the content moreso…
If it’s an issue, maybe a solution would just be I provide some clarification that they aren’t the same mod in my description or something? Or am I just SOL

**Comment by Immodernist** [comment]
I changed the name anyway, so you could use it, I think. However the mod id "endreborn" will remain.

**Comment by Rebel459** [comment]
I’m using end_reborn as my namespace anyway so no issue there, just glad that all’s good
