### ISSUE TITLE
Crash when trying to enchant ender boots in an anvil

### ISSUE THREAD

**Issue by ElRichiRicon** [Immodernist/Endorium#5]
Tested with only this mod, version 1.1.0 for neoforge 1.20.1

The game crashes upon placing an enchanted book on the second slot with the ender boots on the first slot.

Other tools this mod adds don't crash. Enchanting in an enchanting table also works fine.

[crashlog](https://pastebin.com/FDKdMyNH)

**Comment by Immodernist** [comment]
Thank you. Will be fixed soon for 1.20.x and fixed in 1.21.
